name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh
      - run: source ~/.zkm-toolchain/env && cd crates/test-artifacts && cargo build && cd ../..
      - run: rustup component add clippy
      - run: cargo clippy --all-targets -- -D warnings
  test_github_hosted:
    name: Cargo Test (ghithub hosted)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh
      - run: |
          set -e
          source ~/.zkm-toolchain/env
          for pkg in zkm-core-executor zkm-curves zkm-derive zkm-primitives zkm-prover \
              zkm-recursion-circuit zkm-recursion-compiler zkm-recursion-core \
              zkm-recursion-gnark-ffi zkm-stark zkm-zkvm zkm-lib; do
            cargo test -r -p $pkg
          done
        env:
          RUSTFLAGS: "-C target-cpu=native"
  test_self_hosted:
    name: Cargo Test (self hosted)
    concurrency:
      group: ci-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          set -e
          for pkg in zkm-core-machine zkm-sdk zkm-verifier; do
            cargo test -r -p $pkg
          done
        env:
          RUSTFLAGS: "-C target-cpu=native"
